--- #YAML:1.0
# META.yml
#
# $Id: META.yml,v 1.5 2005/01/28 20:57:42 lolo Exp $

name:         Palm-SMS
version:      0.02
license:      GPL
installdirs:  site
distribution_type: module
requires:
  Palm::Raw 0

recommends:
  Palm::PDB 0
  Getopt::Long 0
  Pod::Usage 0
  Date::Format 0
  File::Basename 0
  Text::Wrap 0
