--- #YAML:1.0
name:               Palm-SMS
version:            0.03
abstract:           parse SMS database files
author:
    - Lorenzo Cappelletti <lorenzo.cappelletti@email.it>
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
requires:
    Date::Format:    0
    File::Basename:  0
    Getopt::Long:    0
    Palm::PDB:       0
    Palm::Raw:       0
    Pod::Usage:      0
    Test::More:      0
    Text::Wrap:      0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.48
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
